### ISSUE TITLE
Commands fail

### ISSUE THREAD

**Issue by SajidZakaria** [Skelmis/DPY-Ticket-Bot#10]
**Describe the bug**
-new fails with a traceback given below. Similar happens with -setup. I have tried setting the custom ids and variables as necessary, tried the ids to be both int or string. Fails in both cases.

```
Ignoring exception in command new:
Traceback (most recent call last):
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/sajid/Projects/Fiverr/DPY-Ticket-Bot/bot.py", line 80, in new
    await ctx.ticket.create_ticket(subject=subject)
  File "/home/sajid/Projects/Fiverr/DPY-Ticket-Bot/utils/ticket.py", line 79, in create_ticket
    channel = await guild.create_text_channel(
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/guild.py", line 948, in create_text_channel
    data = await self._create_channel(name, overwrites, ChannelType.text, category, reason=reason, **options)
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/guild.py", line 844, in _create_channel
    'id': target.id
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/sajid/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

```

**Comment by Skelmis** [comment]
Thanks for this. Can you please provide some more details for me.
What version of discord.py are you using?
Is the id being used correct?

Cheers

**Comment by SajidZakaria** [comment]
I am using discord.py 1.7.3
I checked everything multiple times, the ids are okay I guess.

**Comment by Skelmis** [comment]
Sweet, thanks. I will take a look tonight and see if I can reproduce this error or atleast add more logging to debug

**Comment by Skelmis** [comment]
Please update to the latest version and try again. 

It should hopefully be resolved, however in the unlikely event it is not just leave a comment here and I will reopen this for you @SajidZakaria

**Comment by SajidZakaria** [comment]
Cool, it's working perfectly. Thanks a lot.
