### ISSUE TITLE
Im stupid lol

### ISSUE THREAD

**Issue by Jerbyyy0** [Skelmis/DPY-Ticket-Bot#14]
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from utils import MyContext, Ticket, JsonStore, SqliteStore
  File "/home/bots/discord/JerbyDC/Ticket/utils/__init__.py", line 1, in <module>
    from .custom_context import MyContext
  File "/home/bots/discord/JerbyDC/Ticket/utils/custom_context.py", line 3, in <module>
    from .ticket import Ticket
  File "/home/bots/discord/JerbyDC/Ticket/utils/ticket.py", line 7, in <module>
    from utils.db import Base
  File "/home/bots/discord/JerbyDC/Ticket/utils/db/__init__.py", line 1, in <module>
    from .base import Base
  File "/home/bots/discord/JerbyDC/Ticket/utils/db/base.py", line 1, in <module>
    from typing import Protocol, Union
ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)

**Comment by Skelmis** [comment]
This requires Python3.8 or higher.

@JerbyYT
